// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package datastore

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName     *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType   *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion   *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug         *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce         *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError       *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	VCenterServer       *string           `mapstructure:"vcenter_server" cty:"vcenter_server" hcl:"vcenter_server"`
	Username            *string           `mapstructure:"username" cty:"username" hcl:"username"`
	Password            *string           `mapstructure:"password" cty:"password" hcl:"password"`
	InsecureConnection  *bool             `mapstructure:"insecure_connection" cty:"insecure_connection" hcl:"insecure_connection"`
	Datacenter          *string           `mapstructure:"datacenter" cty:"datacenter" hcl:"datacenter"`
	Name                *string           `mapstructure:"name" cty:"name" hcl:"name"`
	NameRegex           *string           `mapstructure:"name_regex" cty:"name_regex" hcl:"name_regex"`
	Host                *string           `mapstructure:"host" cty:"host" hcl:"host"`
	Cluster             *string           `mapstructure:"cluster" cty:"cluster" hcl:"cluster"`
	Tags                []Tag             `mapstructure:"tag" cty:"tag" hcl:"tag"`
	MostFreeSpace       *bool             `mapstructure:"most_free_space" cty:"most_free_space" hcl:"most_free_space"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"vcenter_server":             &hcldec.AttrSpec{Name: "vcenter_server", Type: cty.String, Required: false},
		"username":                   &hcldec.AttrSpec{Name: "username", Type: cty.String, Required: false},
		"password":                   &hcldec.AttrSpec{Name: "password", Type: cty.String, Required: false},
		"insecure_connection":        &hcldec.AttrSpec{Name: "insecure_connection", Type: cty.Bool, Required: false},
		"datacenter":                 &hcldec.AttrSpec{Name: "datacenter", Type: cty.String, Required: false},
		"name":                       &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"name_regex":                 &hcldec.AttrSpec{Name: "name_regex", Type: cty.String, Required: false},
		"host":                       &hcldec.AttrSpec{Name: "host", Type: cty.String, Required: false},
		"cluster":                    &hcldec.AttrSpec{Name: "cluster", Type: cty.String, Required: false},
		"tag":                        &hcldec.AttrSpec{Name: "tag", Type: cty.Bool, Required: false}, /* TODO(azr): could not find type */
		"most_free_space":            &hcldec.AttrSpec{Name: "most_free_space", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDatasourceOutput struct {
	Name    *string      `mapstructure:"name" cty:"name" hcl:"name"`
	ID      *string      `mapstructure:"id" cty:"id" hcl:"id"`
	Summary *FlatSummary `mapstructure:"summary" cty:"summary" hcl:"summary"`
}

// FlatMapstructure returns a new FlatDatasourceOutput.
// FlatDatasourceOutput is an auto-generated flat version of DatasourceOutput.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DatasourceOutput) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDatasourceOutput)
}

// HCL2Spec returns the hcl spec of a DatasourceOutput.
// This spec is used by HCL to read the fields of DatasourceOutput.
// The decoded values from this spec will then be applied to a FlatDatasourceOutput.
func (*FlatDatasourceOutput) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":    &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"id":      &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
		"summary": &hcldec.BlockSpec{TypeName: "summary", Nested: hcldec.ObjectSpec((*FlatSummary)(nil).HCL2Spec())},
	}
	return s
}

// FlatSummary is an auto-generated flat version of Summary.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatSummary struct {
	Capacity *int64 `mapstructure:"capacity" cty:"capacity" hcl:"capacity"`
	Free     *int64 `mapstructure:"free" cty:"free" hcl:"free"`
}

// FlatMapstructure returns a new FlatSummary.
// FlatSummary is an auto-generated flat version of Summary.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Summary) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatSummary)
}

// HCL2Spec returns the hcl spec of a Summary.
// This spec is used by HCL to read the fields of Summary.
// The decoded values from this spec will then be applied to a FlatSummary.
func (*FlatSummary) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"capacity": &hcldec.AttrSpec{Name: "capacity", Type: cty.Number, Required: false},
		"free":     &hcldec.AttrSpec{Name: "free", Type: cty.Number, Required: false},
	}
	return s
}
