// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatTag is an auto-generated flat version of Tag.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatTag struct {
	Name     *string `mapstructure:"name" required:"true" cty:"name" hcl:"name"`
	Category *string `mapstructure:"category" required:"true" cty:"category" hcl:"category"`
}

// FlatMapstructure returns a new FlatTag.
// FlatTag is an auto-generated flat version of Tag.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Tag) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatTag)
}

// HCL2Spec returns the hcl spec of a Tag.
// This spec is used by HCL to read the fields of Tag.
// The decoded values from this spec will then be applied to a FlatTag.
func (*FlatTag) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":     &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"category": &hcldec.AttrSpec{Name: "category", Type: cty.String, Required: false},
	}
	return s
}
