// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatRemoveVTPMConfig is an auto-generated flat version of RemoveVTPMConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatRemoveVTPMConfig struct {
	RemoveVTPM *bool `mapstructure:"remove_vtpm" cty:"remove_vtpm" hcl:"remove_vtpm"`
}

// FlatMapstructure returns a new FlatRemoveVTPMConfig.
// FlatRemoveVTPMConfig is an auto-generated flat version of RemoveVTPMConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*RemoveVTPMConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatRemoveVTPMConfig)
}

// HCL2Spec returns the hcl spec of a RemoveVTPMConfig.
// This spec is used by HCL to read the fields of RemoveVTPMConfig.
// The decoded values from this spec will then be applied to a FlatRemoveVTPMConfig.
func (*FlatRemoveVTPMConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"remove_vtpm": &hcldec.AttrSpec{Name: "remove_vtpm", Type: cty.Bool, Required: false},
	}
	return s
}
