// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatTagConfig is an auto-generated flat version of TagConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatTagConfig struct {
	Category *string `mapstructure:"category" cty:"category" hcl:"category"`
	Name     *string `mapstructure:"name" cty:"name" hcl:"name"`
	ID       *string `mapstructure:"id" cty:"id" hcl:"id"`
}

// FlatMapstructure returns a new FlatTagConfig.
// FlatTagConfig is an auto-generated flat version of TagConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*TagConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatTagConfig)
}

// HCL2Spec returns the hcl spec of a TagConfig.
// This spec is used by HCL to read the fields of TagConfig.
// The decoded values from this spec will then be applied to a FlatTagConfig.
func (*FlatTagConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"category": &hcldec.AttrSpec{Name: "category", Type: cty.String, Required: false},
		"name":     &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"id":       &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
	}
	return s
}

// FlatTagsConfig is an auto-generated flat version of TagsConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatTagsConfig struct {
	Tags []string        `mapstructure:"tags" cty:"tags" hcl:"tags"`
	Tag  []FlatTagConfig `mapstructure:"tag" cty:"tag" hcl:"tag"`
}

// FlatMapstructure returns a new FlatTagsConfig.
// FlatTagsConfig is an auto-generated flat version of TagsConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*TagsConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatTagsConfig)
}

// HCL2Spec returns the hcl spec of a TagsConfig.
// This spec is used by HCL to read the fields of TagsConfig.
// The decoded values from this spec will then be applied to a FlatTagsConfig.
func (*FlatTagsConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"tags": &hcldec.AttrSpec{Name: "tags", Type: cty.List(cty.String), Required: false},
		"tag":  &hcldec.BlockListSpec{TypeName: "tag", Nested: hcldec.ObjectSpec((*FlatTagConfig)(nil).HCL2Spec())},
	}
	return s
}
