// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatVAppConfig is an auto-generated flat version of VAppConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatVAppConfig struct {
	Properties map[string]string `mapstructure:"properties" cty:"properties" hcl:"properties"`
}

// FlatMapstructure returns a new FlatVAppConfig.
// FlatVAppConfig is an auto-generated flat version of VAppConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*VAppConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatVAppConfig)
}

// HCL2Spec returns the hcl spec of a VAppConfig.
// This spec is used by HCL to read the fields of VAppConfig.
// The decoded values from this spec will then be applied to a FlatVAppConfig.
func (*FlatVAppConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"properties": &hcldec.AttrSpec{Name: "properties", Type: cty.Map(cty.String), Required: false},
	}
	return s
}
