---
blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/vmware/packer-plugin-vsphere/discussions/new/choose
    about: The starting point for questions, assistance, and discussions about this project.
  - name: Packer Plugin Documentation
    url: https://vmware.github.io/packer-plugin-vsphere
    about: Having trouble with this Packer plugin? Check out the plugin documentation.
  - name: Packer Documentation
    url: https://developer.hashicorp.com/packer/
    about: Having trouble with Packer? Check out the product documentation.
